### ISSUE TITLE
 有没有比较全的upos域名

### ISSUE THREAD

**Issue by Potterli20** [cxw620/BiliRoamingX#23]
### 原因

可以加个upos列表，但是我这个感觉不全
https://github.com/Potterli20/file/tree/main/Domains/bilibili

### 功能简述

可以云控例表https://github.com/Potterli20/file/tree/main/Domains/bilibili

### 功能逻辑

应该可以做子页面的叭

**Comment by cxw620** [comment]
你收集的已经是现有全部了. 参考 https://github.com/the1812/Bilibili-Evolved/issues/3234#issuecomment-1504764774
